/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Lexical Cast
 #	author : miyako
 #	2016/02/08
 #
 # --------------------------------------------------------------------------------*/



// --- REAL
void Number_to_text(sLONG_PTR *pResult, PackagePtr pParams);
